config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
  
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 25 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # This line makes these methods available to our views.
  helper_method :current_user, :logged_in?

  # The ||= will optimize this method. It will only do the database request if
  #
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    set_article
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = 'Article successfully deleted'
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only edit and/or delete your own articles"
        redirect_to root_path
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created successufully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin?)
        flash[:danger] = "Only admin can perform that action"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Your login information is incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the alpha blog #{@user.username}!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
  end

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles were destroyed"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:danger] = "You can only edit your own profile"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? && !current_user.admin?
        flash[:danger] = "Only admin users can perform this action"
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gratavar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gratavar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% obj.each do |obj| %>
  <tr>
    <td><%= obj.title %></td>
    <td><%= obj.description %></td>
    <td><%= link_to 'Show', article_path(obj) %></td>
  <% if logged_in? && (current_user == obj.user || current_user.admin?) %>
    <td><%= link_to 'Edit', edit_article_path(obj) %></td>
    <td><%= link_to 'Delete', article_path(obj), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    <td>Categories: <%= render obj.categories%></td>
  <% end %>
  </tr>
  <% end %>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented the article from creating:</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox-inline input-checkbox") { cb.check_box(class: "checkbox" ) + cb.text } %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back to Articles Listing', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit Existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing of All Articles</h1>

<p>
  <%= link_to 'Create New Article', new_article_path %>
</p>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing Selected Article</h1>

<p>Title: <%= @article.title %></p>

<% if @article.user %>
  <ul class="listing">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <li>
          Created by:
        </li>
        <li>
          <%= link_to(gravatar_for(@article.user), user_path(@article.user)) if @article.user %>
        </li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) if @article.user %>
        </li>
        <li>
          <small><%= pluralize(@article.user.articles.count, "article") %></small>
        </li>
      </div>
    </div>
  </ul>
<% end %>

<p>Description: <%= @article.description %></p>

<% if @article.categories.any? %>
  <p>Categories: <%= render @article.categories %></p>
<% end %>

<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
  <%= link_to 'Edit this Article', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back to Articles Listing', articles_path %>

app/views/categories/_category.html.erb
<span class="badge">
  <%= link_to category.name, category_path(category) %> &nbsp
</span>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
<h2>The following errors prevented the category from updating:</h2>
<ul>
  <% @category.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @category do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back to Articles Listing', articles_path %>

app/views/categories/edit.html.erb
<h1>Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Listing All Categories</h1>

<% @categories.each do |category| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">
        <li>
          <%= link_to "#{category.name}", category_path(category) %>
        </li>
        <li>
          <small><%= pluralize(category.articles.count, "article") %></small>
        </li>
      </div>
    </div>
  </ul>
<% end %>

app/views/categories/new.html.erb
<h1>Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Listing of All Articles for <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="row">
    <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
  </div>
<% end %>

<%= render 'articles/article', obj: @category.articles %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://udemy.com">The Complete Ruby on Rails Developer</a>
      by Justin Paro
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand', id: 'logo' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= link_to 'Articles', articles_path, class: 'nav-link' %>
      </li>
      <li>
        <%= link_to 'Users', users_path, class: 'nav-link' %>
      </li>
      <% if logged_in? %>
        <li>
          <%= link_to 'Log Out', logout_path, method: :delete, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'New Article', new_article_path, class: 'dropdown-item' %>
            <%= link_to "Edit Profile", edit_user_path(current_user), class: 'dropdown-item' %>
            <%= link_to "View Profile", user_path(current_user), class: 'dropdown-item' %>
          </div>
        </li>
        <li class='nav-link disabled'>
          <%= current_user.username %>'s Profile <%= "(Admin)" if current_user.admin? %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Categories List', categories_path, class: 'dropdown-item' %>
          <% Category.all.each do |category| %>
            <%= link_to "#{category.name}", category_path(category), class: 'dropdown-item' %>
          <% end %>
        <% if current_user.admin? %>
            <%= link_to 'Create New Category', new_category_path, class: 'dropdown-item' %>
          </div>
        </li>
        <% end %>
      <% else %>
        <li>
          <%= link_to 'Log In', login_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<html>
<head>
<title>       </title>
<style type="text/css">
<!--
h1	{text-align:center;
	font-family:Arial, Helvetica, Sans-Serif;
	}

p	{text-indent:20px;
	}
-->
</style>
</head>
<body bgcolor = "#ffffcc" text = "#000000">
<h1>About this Alpha Blog</h1>

<p>I grabbed this HTML from a website. I just wanted a template that I could
easily copy and paste. This page will most likely include information that will
describe my blog in the future.</p>

<%= link_to 'Home', root_path %>

</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>ALPHA BLOG</h1>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2>The following errors prevented the account from updating:</h2>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account") %>
  </p>

<% end %>

<%= link_to 'Back to Articles Listing', articles_path %>

app/views/users/edit.html.erb
<h1>Edit Your Accout</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Alpha Bloggers</h1>
<% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <li>
          <%= link_to gravatar_for(user), user_path(user) %>
        </li>
        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li>
          <small><%= pluralize(user.articles.count, "article") %></small>
        </li>
        <% if logged_in? && current_user.admin? %>
          <li>
            <%= link_to "Delete this User", user_path(user), method: :delete,
              data: { confirm: "Really delete this user and its articles?" } %>
          </li>
        <% end %>
      </div>
    </div>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>New User Signup</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4><%= @user.username %>'s articles:</h4>

<%= render 'articles/article', obj: @user.articles %>